apiVersion: v1
kind: Pod
metadata:
  name: servicio-sebas-pod
  labels:
    app: servicio-sebas
spec:
  containers:
    - name: servicio-sebas-container
      image: sebastiansalas/servicio-sebas:v1
      ports:
        - containerPort: 3001

---

apiVersion: v1
kind: Service
metadata:
  name: servicio-sebas-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
  selector:
    app: servicio-sebas