apiVersion: v1
kind: Pod
metadata:
  name: orquestador-pod
  labels:
    app: orquestador
spec:
  containers:
    - name: orquestador-container
      image: fredyball/microrquesta:latest
      ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: servicio-orquestador-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: servicio-orquestador