apiVersion: v1
kind: Pod
metadata:
  name: servicio-marce-pod
  labels:
    app: servicio-marce
spec:
  containers:
    - name: servicio-marce-container
      image: marcelounivalle/servicio-marce:latest
      ports:
        - containerPort: 4567

---
apiVersion: v1
kind: Service
metadata:
  name: servicio-marce-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4567
      protocol: TCP
  selector:
    app: servicio-marce
